# Copyright 2026 exdura authors
# SPDX-License-Identifier: Apache-2.0

[package]
name = "exdura"
version = "0.1.0"

[application]
supervisor = "ExduraSupervisor"

[dependencies]
http = { git = "https://github.com/jamesc/beamtalk-http", tag="v0.1.1" }
